UA : "A"
LA : "a"
UB : "B"
LB : "b"
UC : "C"
LC : "c"
UD : "D"
LD : "d"
UE : "E"
LE : "e"
UF : "F"
LF : "f"
UG : "G"
LG : "g"
UH : "H"
LH : "h"
UI : "I"
LI : "i"
UJ : "J"
LJ : "j"
UK : "K"
LK : "k"
UL : "L"
LL : "l"
UM : "M"
LM : "m"
UN : "N"
LN : "n"
UO : "O"
LO : "o"
UP : "P"
LP : "p"
UQ : "Q"
LQ : "q"
UR : "R"
LR : "r"
US : "S"
LS : "s"
UT : "T"
LT : "t"
UU : "U"
LU : "u"
UV : "V"
LV : "v"
UW : "W"
LW : "w"
UX : "X"
LX : "x"
UY : "Y"
LY : "y"
UZ : "Z"
LZ : "z"
BACKSLASH : /\\/
FORWARDSLASH : "/"
WS : " "
TAB : /\t/
EOL1 : /\r/
EOL2 : /\n/
DQ : "\""
SQ : "'"
COMMA : ","
DIGIT : /\d/
LFP : "("
RTP : ")"
LSB : "["
UNDERSCORE : "_"
ASTERISK : "*"
RSB : "]"
LCB : "{"
RCB : "}"
COLON : ":"
SEMICOLON : ";"
PLUS : "+"
MINUS : "-"
PERIOD : "."
QUESTION : "?"
PERCENT : "%"
TILDE : "~"
LFT : "<"
EQ : "="
GT : ">"
DOLLAR : "$"